language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
services:
  - redis-server
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script: "DATABASE_URL=postgresql://postgres:@localhost/myapp_test rspec"
