language: ruby
rvm:
  - 2.2.3
services:
  - redis-server
env:
 - DATABASE_URL=postgresql://postgres:@localhost/tunefl_test
before_script:
  - psql -c 'create database tunefl_test;' -U postgres
script:
  - bundle exec rake db:migrate
  - bundle exec rake
notifications:
  email:
    recipients:
      - tiredpixel@posteo.de
