language: ruby
rvm:
  - 2.1.0
services:
  - redis-server
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script:
  - DATABASE_URL=postgresql://postgres:@localhost/myapp_test bundle exec rake db:migrate --trace
  - DATABASE_URL=postgresql://postgres:@localhost/myapp_test bundle exec rspec
notifications:
  email:
    recipients:
      - tp@tiredpixel.com
