language: ruby
rvm:
  - 2.2.3
services:
  - redis-server
env:
 - DATABASE_URL=postgresql://tunefl_test:password@localhost/tunefl_test LOG_LEVEL=DEBUG
before_script:
  - psql -U postgres -c "CREATE ROLE tunefl_test LOGIN PASSWORD 'password'"
  - psql -U postgres -c "CREATE DATABASE tunefl_test OWNER tunefl_test"
  - bundle exec rake db:migrate
script:
  - bundle exec rake
