language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
services:
  - redis-server
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script:
  - DATABASE_URL=postgresql://postgres:@localhost/myapp_test bundle exec rake db:migrate --trace
  - DATABASE_URL=postgresql://postgres:@localhost/myapp_test bundle exec rspec
notifications:
  email:
    recipients:
      - tp@tiredpixel.com
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode